# LUYỆN TẬP NUMPY - PHẦN 1

In [57]:
import numpy as np
from typing import List, Dict, Tuple, Optional

## Bài 1: Khởi tạo vector
Khởi tạo một vector gồm `n` phần tử gồm toàn số 0.

Ví dụ:

Input:
```
n = 5
```

Output:
```
array([0., 0., 0., 0., 0.])
```

In [58]:
def init_zeros(n: int) -> np.ndarray:
    ### BEGIN SOLUTION
    return np.zeros(n)
    ### END SOLUTION

In [59]:
# Sample Input & Output
init_zeros(5)

array([0., 0., 0., 0., 0.])

In [60]:
# Public Test
assert init_zeros(5).shape == (5, )
assert np.sum(abs(init_zeros(5) - np.array([0, 0, 0, 0, 0]))) == 0

## Bài 2: Khởi tạo vector
Khởi tạo một vector gồm `n` phần tử gồm toàn số 1.

Ví dụ:

Input:
```
n = 5
```

Output:
```
array([1, 1, 1, 1, 1])
```

In [61]:
def init_ones(n: int) -> np.ndarray:
    ### BEGIN SOLUTION
    return np.ones(n)
    ### END SOLUTION

In [62]:
# Sample Input & Output
init_ones(5)

array([1., 1., 1., 1., 1.])

In [63]:
# Public Test
assert init_ones(5).shape == (5, )
assert np.sum(abs(init_ones(5) - np.array([1, 1, 1, 1, 1]))) == 0

## Bài 3: Khởi tạo vector
Khởi tạo một vector gồm `n` phần tử gồm toàn số `x`.

Ví dụ:

Input:
```
n = 5
x = 3.5
```

Output:
```
array([3.5, 3.5, 3.5, 3.5, 3.5])
```

In [64]:
def init_all_x(n: int, x: float) -> np.ndarray:
    ### BEGIN SOLUTION
    return np.full(n, x)
    ### END SOLUTION

In [65]:
# Sample Input & Output
init_all_x(5, 3.5)

array([3.5, 3.5, 3.5, 3.5, 3.5])

In [66]:
# Public Test
assert init_all_x(5, 3.5).shape == (5, )
assert np.sum(abs(init_all_x(5, 3.5) - np.array([3.5, 3.5, 3.5, 3.5, 3.5]))) == 0

## Bài 4: Khởi tạo vector
Khởi tạo một vector có số phần tử là `n` gồm các số nguyên tăng dần từ `0..n-1`.

Ví dụ:

Input:
```
n = 5
```

Output:
```
array([0, 1, 2, 3, 4])
```

In [67]:
def init_range(n: int) -> np.ndarray:
    ### BEGIN SOLUTION
    return np.arange(n)
    ### END SOLUTION

In [68]:
# Sample Input & Output
init_range(5)

array([0, 1, 2, 3, 4])

In [69]:
# Public Test
assert init_range(5).shape == (5, )
assert np.sum(abs(init_range(5) - np.array([0,1,2,3,4]))) == 0

## Bài 5: Khởi tạo vector
Khởi tạo một vector có số phần tử là `n` gồm các số nguyên tăng dần từ `x, x+1,...,x+n-1` (chuỗi số bắt đầu từ `x`)

Ví dụ:

Input:
```
n = 5
x = 3.5
```

Output:
```
array([3.5, 4.5, 5.5, 6.5, 7.5])
```

In [70]:
def init_range(n: int, x: int) -> np.ndarray:
    ### BEGIN SOLUTION
    return np.arange(x, x+n)
    ### END SOLUTION

In [71]:
# Sample Input & Output
init_range(5, 3.5)

array([3.5, 4.5, 5.5, 6.5, 7.5])

In [72]:
# Public Test
assert init_range(5, 3).shape == (5, )
assert np.sum(abs(init_range(5, 3) - np.array([3, 4, 5, 6, 7]))) == 0

## Bài 6: Khởi tạo ma trận
Khởi tạo ma trận kích thước `m x n` gồm toàn số `K`.

Ví dụ:

Input:
```
m = 3
n = 4
K = 5
```

Output:
```
array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])
```

In [73]:
def init_mat_K(m: int, n: int, K: float) -> np.ndarray:
    ### BEGIN SOLUTION
    return np.full((m, n), K)
    ### END SOLUTION

In [74]:
# Sample Input & Output
init_mat_K(3, 4, 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [75]:
# Public Test
assert init_mat_K(2,3,4).shape == (2, 3)
assert np.sum(abs(init_mat_K(2,3,4) - np.array([[4, 4, 4], [4, 4, 4]]))) == 0

## Bài 7: Khởi tạo ma trận
Khởi tạo ma trận kích thước `m x n` gồm tăng dần từ trái sang phải, từ trên xuống dưới. Phần tử nhỏ nhất bắt đầu từ 1.

Ví dụ:

Input:
```
m = 2
n = 4
```

Output:
```
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])
```

In [76]:
def init_mat_increase(m: int, n: int) -> np.ndarray:
    ### BEGIN SOLUTION
    sequence = np.arange(1, m*n + 1)
    matrix = sequence.reshape((m, n))
    return matrix
    ### END SOLUTION

In [77]:
# Sample Input & Output
init_mat_increase(2, 4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [78]:
# Public Test
assert init_mat_increase(2,3).shape == (2, 3)
assert np.sum(abs(init_mat_increase(2,3) - np.array([[1, 2, 3], [4, 5, 6]]))) == 0

## Bài 8: Tích vô hướng 2 vector
Viết hàm `solution` nhận vào 2 List `a` và `b` có kiểu dữ liệu là `float`, tính tích vô hướng giữa hai vector `a` và `b`.

Ví dụ:

Input:
```
a = [1, 2]
b = [3, 4]
```

Output:
```
11
```

In [79]:
def product_on_list(a: List[int], b: List[int]) -> np.ndarray:
    # Step 1: Convert a and b to numpy arrays
    ### BEGIN SOLUTION
    a_array = np.array(a, dtype=float)
    b_array = np.array(b, dtype=float)
    ### END SOLUTION

    # Step 2: Calculate dot product using the dot function
    ### BEGIN SOLUTION
    return np.dot(a_array, b_array)
    ### END SOLUTION

In [80]:
# Sample Input & Output
product_on_list([1, 2], [2, 3])

8.0

In [81]:
# Public Test
assert product_on_list([1, 2], [2, 3]) == 8
assert product_on_list([1, 2], [0, 0]) == 0

## Bài 9: Tích vô hướng 2 ma trận
Viết hàm nhận vào hai *ma trận* `X` và *ma trận* `W`, trả về giá trị tích `M` (dot product) theo công thức sau:
```
M = (x^T)W
```
Trong đó, `x^T` là phép chuyển vị của `x`. Cần kiểm tra số chiều để bảo đảm phép tính luôn tính được trước khi thực hiện phép tính, trả về giá trị `None` nếu số chiều không tương thích.

Ví dụ:


Input:
```
X = np.array([
    [1, 1, 1],
    [0, 0, 0]]
)

W = np.array([
    [1, 1, 1],
    [0, 0, 0]]
)
```

Output:
```
[[1, 1, 1],
 [1, 1, 1],
 [1, 1, 1]]
```

In [82]:
def product_vec_mat(X: np.ndarray, W: np.ndarray) -> Optional[np.ndarray]:
    ### BEGIN SOLUTION
    X_T = X.T
    M = np.dot(X_T, W)
    return M

    ### END SOLUTION

In [83]:
# Sample Input & Output
X = np.array([
  [1, 1, 1],
  [0, 0, 0]
])
W = np.array([
  [1, 1, 1],
  [0, 0, 0]
])
product_vec_mat(X, W)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [84]:
# Public Test
X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
W = np.array([
    [7, 8, 9],
    [10, 11, 12]
])

assert np.sum(abs(product_vec_mat(X, W)-np.array([
    [47, 52, 57],
    [64, 71, 78],
    [81, 90, 99]
]))) < 0.0001

## Bài 10: Tổng các ma trận và vector
Viết hàm nhận vào hai ma trận `X` và `W`, trả về giá trị `M` theo công thức sau:
```
M = 2 (X^T + W).X
```
Trong đó `X^T` là phép chuyển vị của `X`. Cần kiểm tra số chiều để bảo đảm phép tính luôn tính được trước khi thực hiện phép tính, trả về giá trị `None` nếu số chiều không tương thích.

Ví dụ:


Input:
```
X = np.array([
    [1, 1],
    [0, 0]
])

W = np.array([
    [1, 1],
    [0, 0]
])
```

Output:
```
array([[4, 4],
       [2, 2]])
```

In [85]:
def prod_sum_mat(x: np.ndarray, w: np.ndarray) -> Optional[np.ndarray]:
    ### BEGIN SOLUTION
    x_transpose = x.T
    sum_x_w = x_transpose + w
    product = np.dot(sum_x_w, x)
    m = 2 * product
    return m
    ### END SOLUTION

In [86]:
# Public Test
X = np.array([
  [1, 1],
  [2, 3],
  [5, 4]
])

W = np.array([
  [1, 2, 3],
  [4, 5, 6]
])

assert np.sum(abs(prod_sum_mat(X, W)-np.array([
    [100, 92],
    [142, 138]
]))) < 0.0001

# LUYỆN TẬP NUMPY - PHẦN 2

## Bài 1: Gửi tiết kiệm
Tính số tiền còn lại trong tài khoản ngân hàng với đầu vào là
danh sách các số tiền giao dịch, tương ứng là sẽ có danh sách
các loại giao dịch gửi tiền (ký hiệu bằng chuỗi 'D'), rút tiền
(ký hiệu bằng chuỗi 'W')

**Input:**
   - moneys: kiểu numpy array, chứa danh sách các số tiền giao dịch
   (gửi và rút khỏi tài khoản)
   - types: kiểu numpy array, chứa danh sách các loại giao dịch
   (gửi ký hiệu là 'D', rút ký hiệu là 'W')

**Output:**
   - Kiểu số thực, số tiền còn lại trong tài khoản

Ví dụ:

Input:
```
moneys = [400.0, 100.0, 200.0]
types = ['D', 'W', 'D']
```

Output:
```
500.0
```

In [87]:
def balance(moneys: np.ndarray, types: np.ndarray) -> float:
    ### BEGIN SOLUTION
    balance = 0.0
    for money, type in zip(moneys, types):
        if type == 'D':
            balance += money
        elif type == 'W':
            balance -= money
    return balance
    ### END SOLUTION

In [88]:
# Sample Input & Output
balance(np.array([400.0, 100.0, 200.0]), np.array(['D', 'W', 'D']))

500.0

In [89]:
# Public Test
assert balance(np.array([400.0, 100.0, 200.0]), np.array(['D', 'W', 'D'])) == 500

## Bài 2: Điểm trung bình
Tính điểm trung bình của một bạn sinh viên biết trước danh sách các điểm số và số tín chỉ của từng môn học.

**Input:**
   - marks: kiểu List, gồm *n* phần tử. Đây là điểm các môn của một sinh viên.
   - credits: kiểu List, gồm *n* phần tử. Đây là số tín chỉ lần lượt của các môn.   
   
**Output:**
   - Kiểu số thực, điểm trung bình của các môn học của sinh viên

Ví dụ:

Input:
```
marks = [8.0, 9.0, 10.0]
credits = [2, 2, 1]
```

Output:
```
8.8
```

In [90]:
def gpa_one_student(marks: List[float], weights: List[int]) -> float:
    result = 0
    ### BEGIN SOLUTION
    total_weighted_marks = sum(mark * weight for mark, weight in zip(marks, weights))
    total_weights = sum(weights)
    result = total_weighted_marks / total_weights if total_weights > 0 else 0
    ### END SOLUTION
    return result

In [91]:
# Sample Input & Output
marks = [8.0, 9.0, 10.0]
credits = [2, 2, 1]
gpa_one_student(marks, credits)

8.8

In [92]:
# Public Test
assert abs(gpa_one_student([10, 9, 8], [4, 3, 2])-9.222222222222221) < 0.000001

## Bài 3:
Đếm số lượng sinh viên có điểm số không dưới K điểm cho trước của một lớp học.

**Input:**

    - marks: kiểu numpy array, kích thước 1 x n. Đây là điểm toán cả n sinh viên trong lớp.
    - K: kiểu số thực, điểm chuẩn.
   
**Output:**

    - Kiểu số nguyên, số lượng sinh viên trong lớp đạt từ K điểm trở lên

In [93]:
def pass_exam(marks: List[int], K: int) -> int:
    ### BEGIN SOLUTION
    if not isinstance(marks, np.ndarray):
        marks = np.array(marks)
    pass_marks = marks[marks >= K]
    count = len(pass_marks)
    return count

    ### END SOLUTION

In [94]:
# Sample Input & Output
marks = np.array([4.0, 9.0, 5.0])
K = 5
pass_exam(marks, K)

2

In [95]:
# Public Test
assert pass_exam(np.array([3.0, 9.5, 4.5]), 5.0) == 1

## Bài 4:
Tính điểm trung bình cao nhất của một lớp học biết trước danh sách các điểm số và số tín chỉ
cho từng môn học của một lớp.

**Input:**
   - marks: kiểu numpy array, kích thước m x n. Đây là điểm các môn của một lớp học. Trong đó, m là số sinh viên, n là số môn học
   - credits: kiểu numpy array, kích thước 1 x n. Đây là số tín chỉ lần lượt của các môn.
   
**Output:**
   - Kiểu số thực, điểm trung bình của sinh viên cao nhất.

Ví dụ:

Input:
```
marks = np.array(
   [[8.0, 9.0, 10.0],
   [7.0, 9.0, 8.0],
   [8.0, 8.0, 8.0],
   [10.0, 9.0, 7.0],
   [9.0, 9.0, 10.0]
])

credits = np.array([2,2,1])
```

Output:
```
9.2
```

In [96]:
def max_gpa(marks: List[float], credits: List[int]) -> float:
    ### BEGIN SOLUTION
    total_points = np.dot(marks, credits)
    total_credits = np.sum(credits)
    gpas = total_points / total_credits
    max_gpa = np.max(gpas)
    return max_gpa
    ### END SOLUTION

In [97]:
# Sample Input & Output
marks = np.array(
   [[8.0, 9.0, 10.0],
   [7.0, 9.0, 8.0],
   [8.0, 8.0, 8.0],
   [10.0, 9.0, 7.0],
   [9.0, 9.0, 10.0]
])
credits = np.array([2,2,1])
max_gpa(marks, credits)

9.2

In [98]:
# Public Test
marks = np.array(
   [[4.0, 9.0, 4.5],
   [5.0, 8.0, 4.5],
   [6.0, 7.0, 7.5],
   [7.0, 6.0, 7.5],
   [8.0, 5.0, 4.5]
])
credits = np.array([2,1,2])
assert abs(max_gpa(marks, credits)-7.0) < 0.000001

## Bài 5:
Tính điểm trung bình tích luỹ của từng sinh viên trong lớp học biết trước
danh sách các điểm số và số tín chỉ cho từng môn học của một lớp.

**Lưu ý:** khi tính điểm trung bình ta sẽ loại bỏ các điểm và các tín chỉ của môn dưới 5 điểm (rớt).

**Công thức tính điểm trung bình tích lũy:**
   - ĐTBTL = (điểm môn 1 * số tín chỉ môn 1 + ... + điểm môn n * số tín chỉ môn n) / tổng số tín chỉ

**Input:**
   - marks: kiểu numpy array, kích thước m x n. Đây là điểm các môn của một lớp học.
   Trong đó, m là số sinh viên, n là số môn học
   - credits: kiểu numpy array, kích thước 1 x n. Đây là số tín chỉ lần lượt của các môn.

**Output:**
   - Kiểu numpy array, kích thước 1 x m, chứa điểm trung bình của các bạn sinh viên trong lớp.

Ví dụ:

Input:
```
marks = np.array([
    [8.0, 9.0, 10.0],
    [4.0, 9.0, 8.0],
    [8.0, 3.0, 8.0],
    [10.0, 9.0, 5.0],
    [9.0, 9.0, 4.0]
])

credits = np.array([2, 2, 1])
```

Output:
```
array([8.8, 8.66666667, 8., 8.6, 9.])
```

In [99]:
def gpa_of_pass(marks: np.ndarray, credits: List[int]) -> np.ndarray:
    ### BEGIN SOLUTION
    passed = marks >= 5
    total_points = np.sum(marks * credits * passed, axis=1)
    total_credits_passed = np.sum(credits * passed, axis=1)
    gpa = np.where(total_credits_passed > 0, total_points / total_credits_passed, 0)
    return gpa;
    ### END SOLUTION

In [100]:
# Sample Input & Output
marks = np.array(
    [[8.0, 9.0, 10.0],
    [4.0, 9.0, 8.0],
    [8.0, 3.0, 8.0],
    [10.0, 9.0, 5.0],
    [9.0, 9.0, 4.0]])
credits = np.array([2,2,1])
gpa_of_pass(marks, credits)

array([8.8       , 8.66666667, 8.        , 8.6       , 9.        ])

In [101]:
# Public Test
marks = np.array(
   [[4.0, 9.0, 4.5],
   [5.0, 8.0, 4.5],
   [6.0, 7.0, 7.5],
   [7.0, 6.0, 7.5],
   [8.0, 5.0, 4.5]])
credits = np.array([2,1,2])
assert np.sum(abs(gpa_of_pass(marks, credits)-np.array([9., 6., 6.8, 7.0, 7.0]))) < 0.000001

# LUYỆN TẬP OOP - PHẦN 1

Viết chương trình cài đặt 3 lớp (class) sau: `Geometry` , `Square`, và `Round`. Cho biết 2 class `Square` và `Round` kế thừa từ class `Geometry`.

Cả 3 class đều có những thuộc tính, phương thức sau:

- Thuộc tính:
    - `property` (`float`): có thể xem là độ dài cạnh (đối với hình vuông) hoặc bán kính (đối với hình tròn).

- Phương thức:
    - Hàm khởi tạo `__init__`.
    - Hàm tính diện tích `calculate_area`.

Ví dụ về hàm `calculate_area` của class `Square`:
- Thuộc tính của object:
```
property = 2
```
- Input:
```
# no input
```
- Output:
```
4
```

Ví dụ về hàm `calculate_area` của class `Round`:
- Thuộc tính của object:
```
property = 2
```
- Input:
```
# no input
```
- Output:
```
12.56637
```

**Lưu ý:** Dùng `math.pi` để tính diện tích, kết quả làm tròn 5 chữ số thập phân.

**Yêu cầu 1:** Cài đặt class `Geometry`. Cài đặt phương thức `calculate_area` là `abstract method`.

In [102]:
from abc import abstractmethod
from typing import List, Dict, Tuple, Optional

### BEGIN SOLUTION
class Geometry():
    def __init__(self, property: float):
        self.property = property

    @abstractmethod
    def calculate_area(self):
        pass
### END SOLUTION

In [103]:
# Public Test
geometry_obj = Geometry(2)
assert geometry_obj.property == 2

**Yêu cầu 2:** Cài đặt class `Square` kế thừa từ class `Geometry`.

In [104]:
class Square(Geometry):
    def __init__(self, property: float) -> None:
        # Call the __init__ method of the parent class using `super()`
        ### BEGIN SOLUTION
        super().__init__(property)
        ### END SOLUTION

    # Implement the `calculate_area` method
    ### BEGIN SOLUTION
    def calculate_area(self):
        return round(self.property ** 2, 5)
    ### END SOLUTION

In [105]:
# Public Test
square_obj = Square(2)
assert square_obj.calculate_area() == 4

**Yêu cầu 3:** Cài đặt class `Round` kế thừa từ class `Geometry`. Lưu ý sử dụng `math.pi` và làm tròn kết quả 5 chữ số thập phân.

In [106]:
import math

class Round(Geometry):
    def __init__(self, property: float) -> None:
        # Call the __init__ method of the parent class using `super()`
        ### BEGIN SOLUTION
        super().__init__(property)
        ### END SOLUTION

    # Implement the `calculate_area` method
    ### BEGIN SOLUTION
    def calculate_area(self):
        return round(math.pi * self.property ** 2, 5)
    ### END SOLUTION

In [107]:
# Public Test
square_obj = Round(2)
assert square_obj.calculate_area() == 12.56637

# LUYỆN TẬP OOP - PHẦN 2

Viết chương trình cài đặt lớp (class) `PhanSo` (Phân số).

Lớp (class) có những thuộc tính, phương thức sau:

- Thuộc tính:
    - `tu_so` (int): Tử số.
    - `mau_so` (int): Mẫu số (có điều kiện khác `0`, khi khai báo sử dụng câu lệnh `assert` để kiểm tra).

- Phương thức:
    - Hàm khởi tạo `__init__`: Lưu ý trả ra lỗi nêu khai báo mẫu số bằng `0`. Lưu ý rút gọn phân số.
    - Hàm tính toán: `cong`, `tru`:
        - Cập nhật `tu_so` và `mau_so` của object, lưu ý rút gọn phân số.
    - Hàm rút gọn phân số: `rut_gon`.
    
**Quy ước:** Nếu tử số bằng `0` thì gán mẫu số bằng `1`.

Ví dụ số 1 về hàm `__init__`:
- Input:
```
tu_so = 2
mau_so = 4
```
- Output:
```
# no output
```
- Thuộc tính của object sau khi chạy:
```
tu_so = 1
mau_so = 2
```

Ví dụ số 2 về hàm `__init__`:
- Input:
```
tu_so = 2
mau_so = 0
```
- Output:
```
# error
```
- Thuộc tính của object sau khi chạy:
```
# error
```

Ví dụ về hàm `cong` (cộng phân số):
- Thuộc tính của object:
```
tu_so = 1
mau_so = 3
```
- Input:
```
other = PhanSo(1, 3)
```
- Output:
```
# no output
```
- Thuộc tính của object sau khi chạy:
```
tu_so = 2
mau_so = 3
```

Ví dụ về hàm `tru` (trừ phân số):
- Thuộc tính của object:
```
tu_so = 2
mau_so = 3
```
- Input:
```
other = PhanSo(1, 3)
```
- Output:
```
# no output
```
- Thuộc tính của object sau khi chạy:
```
tu_so = 1
mau_so = 3
```

**Yêu cầu:** Thực hiện cài đặt class `PhanSo`.

In [108]:
import math
from typing import List, Dict, Tuple, Optional


class PhanSo:
    def __init__(self, tu_so: int, mau_so: int) -> None:
        # Use `assert` statement to check the denominator
        ### BEGIN SOLUTION
        assert mau_so != 0
        ### END SOLUTION

        # Initialize attributes `tu_so`, `mau_so`
        ### BEGIN SOLUTION
        self.tu_so = tu_so
        self.mau_so = mau_so
        ### END SOLUTION

        # Simplify the fraction
        self.rut_gon()

    def rut_gon(self) -> None:
        # Use `math.gcd` to find the greatest common divisor
        ### BEGIN SOLUTION
        ucln = math.gcd(self.tu_so, self.mau_so)
        self.tu_so //= ucln
        self.mau_so //= ucln
        if self.tu_so == 0:
            self.mau_so = 1
        ### END SOLUTION

    def cong(self, other: 'PhanSo') -> None:
        ### BEGIN SOLUTION
        self.tu_so = self.tu_so * other.mau_so + other.tu_so * self.mau_so
        self.mau_so = self.mau_so * other.mau_so
        self.rut_gon()
        ### END SOLUTION

    def tru(self, other: 'PhanSo') -> None:
        ### BEGIN SOLUTION
        self.tu_so = self.tu_so * other.mau_so - other.tu_so * self.mau_so
        self.mau_so = self.mau_so * other.mau_so
        self.rut_gon()
        ### END SOLUTION

In [109]:
# Public Test
phan_so_obj = PhanSo(2, 4)
assert phan_so_obj.tu_so == 1
assert phan_so_obj.mau_so == 2

In [110]:
# Public Test
try:
    has_error = False
    PhanSo(1, 0)
except:
    has_error = True

assert has_error

In [111]:
# Public Test
phan_so_obj = PhanSo(2, 3)
phan_so_obj.tru(PhanSo(1, 3))
assert phan_so_obj.tu_so == 1
assert phan_so_obj.mau_so == 3